version: "2"
services:

    app:
        build: '.'
        depends_on:
            - database
        ports:
            - 0.0.0.0:8099:9000
        env_file: .env
        volumes:
            - '.:/go'

    database:
        image: postgres:9.4
        env_file: .env
        environment:
            - PGPASSWORD=example
        ports:
            - "5432"
        volumes:
            - dbdata:/var/lib/postgresql

volumes:
    dbdata:
        driver: local